// prowork-react/src/componenets/NewIssueComponent.js
import React from 'react';
import { connect } from 'react-redux';
import { Link } from 'react-router-dom'
import { LoggedHeaderComponent } from './LoggedHeaderComponent';
import { getUsersAction } from '../actions/issue.actions';
import { createNewIssue } from '../services/issue.service';

class NewIssueComponent extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            dueDateSelected: false,
            type: 'TASK',
            dueDate: null
        };
    }

    componentDidMount() {
        if (this.props.users) {
            this.props.dispatch(getUsersAction(this.props.token));
        }
    }

    handleChange = (event) => {
        let key = event.target.id;
        let value = event.target.value;
        this.setState({
            [key]: value
        });
    }

    changeDueDateInputEnabled = () => {
        this.setState({
            dueDateSelected: !this.state.dueDateSelected
        });
    }

    submitNewIssue = (event) => {

        event.preventDefault();

        let state = this.state;

        if (!state || !state.name || !state.type || !state.reviewedBy || !state.assignedTo || !state.description || state.dueDateSelected == null || (state.dueDateSelected != null && !state.name)){
            console.log('Error');
        }else{
            createNewIssue(this.state, this.props.token).then((response) => {
                this.props.history.push('/home');
            });
        }

    }

    discard = (event) => {
        event.preventDefault();
        this.props.history.push('/home');
    }

    render() {
        return (
            <div>
                <LoggedHeaderComponent />
                <div className="container">
                    <form onSubmit={this.submitNewIssue}>
                        <div className="form-group row">
                            <label className="col-sm-3 col-form-label">Name:</label>
                            <div className="col-sm-9">
                                <input id="name" className="form-control" onChange={this.handleChange} />
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-sm-3 col-form-label">Type:</label>
                            <div className="col-sm-9">
                                <select id="type" className="form-control" onChange={this.handleChange}>
                                    <option value="TASK">Task</option>
                                    <option value="STORY">Story</option>
                                    <option value="BUG">Bug</option>
                                </select>
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-sm-3 col-form-label">Reviewed By:</label>
                            <div className="col-sm-9">
                                <select id="reviewedBy" className="form-control" onChange={this.handleChange}>
                                    <option value="No one selected">No one selected</option>
                                    {
                                        this.props.users.map((user) => {
                                            return (<option key={`review-${user.username}`} value={user.username}>
                                                {user.username}
                                            </option>)
                                        })
                                    }
                                </select>
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-sm-3 col-form-label">Assigned To:</label>
                            <div className="col-sm-9">
                                <select id="assignedTo" className="form-control" onChange={this.handleChange}>
                                    <option value="No one selected">No one selected</option>
                                    {
                                        this.props.users.map((user) => {
                                            return (<option key={`assign-${user.username}`} value={user.username}>
                                                {user.username}
                                            </option>)
                                        })
                                    }
                                </select>
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-sm-3 col-form-label">Description:</label>
                            <div className="col-sm-9">
                                <textarea id="description" maxLength="1000" rows="10" className="form-control" onChange={this.handleChange}>
                                </textarea>
                            </div>
                        </div>
                        <div className="form-group row">
                            <label className="col-sm-3 col-form-label">Due Date:</label>
                            <div className="col-sm-4">
                                <input id="dateDue" type="date" disabled={!this.state.dueDateSelected} onChange={this.handleChange} />
                            </div>
                            <div>
                                <input id="dueDateSelected" type="checkbox" onChange={() => this.changeDueDateInputEnabled()} />
                            </div>
                        </div>
                        <div>
                            <button className="btn btn-dark" type="submit">Submit Issue</button>
                            <button className="btn btn-danger ml-3" onClick={this.discard}>Discard Issue</button>
                        </div>
                    </form >
                </div >
            </div>
        )
    }

}

function mapStateToProps(state) {
    const { loggingIn, loggedIn, token, username } = state.accessReducer;
    const { issues, users } = state.issueReducer;
    return { loggingIn, loggedIn, token, username, issues, users }
}

const newIssueComp = connect(mapStateToProps)(NewIssueComponent);
export { newIssueComp as NewIssueComponent }

// prowork-app/src/app/new-issue/new-issue.component.ts
import {Component, OnInit} from '@angular/core';
import {FormBuilder, FormGroup, Validators} from "@angular/forms";
import {User} from "../model/user";
import {Router} from "@angular/router";
import {IssueService} from "../issue.service";
import {Issue} from "../model/issue";
import moment = require("moment");

@Component({
  selector: 'app-new-issue',
  templateUrl: './new-issue.component.html',
  styleUrls: ['./new-issue.component.css']
})
export class NewIssueComponent implements OnInit {

  issueForm: FormGroup;
  users: User[];
  usersReady = false;

  constructor(private fb: FormBuilder, private router: Router,
              private issueService: IssueService) {
  }

  ngOnInit() {
    this.issueService.getAllUsers().subscribe(
      (users: User[]) => {
        this.usersReady = true;
        this.users = users;
        const date: string = moment().format('YYYY-MM-DD');
        console.log(date);
        this.issueForm = this.fb.group({
          name: ['', [Validators.required]],
          type: ['TASK', [Validators.required]],
          reviewedBy: ['No one selected', [Validators.required]],
          assignedTo: ['No one selected', [Validators.required]],
          description: ['', [Validators.required]],
          dueDate: [{value: '2018-01-14', disabled: true}],
          dueDateSelected: [false]
        });
      },
      (error: any) => console.error(error)
    );
  }

  onSubmit() {
    const date = moment(this.issueForm.value.dueDate, 'YYYY-MM-DD');

    const formValue = this.issueForm.value;
    const formData = new FormData();
    formData.set('name', formValue.name);
    formData.set('type', formValue.type);
    formData.set('reviewedBy', formValue.reviewedBy);
    formData.set('assignedTo', formValue.assignedTo);
    formData.set('description', formValue.description);
    formData.set('dueDate', date.format('DD.MM.YYYY'));
    formData.set('dueDateSelected', formValue.dueDateSelected);

    this.issueService.createNewIssue(formData)
      .subscribe((response: Issue) => this.router.navigateByUrl('/home'),
        (error: any) => console.error(error));
  }

  discard() {
    this.router.navigateByUrl('/home');
  }

  changeDueDateInputEnabled(enabled: boolean): void {
    const control = this.issueForm.controls['dueDate'];
    enabled ? control.enable() : control.disable();

  }

}

<app-logged-header></app-logged-header>
<div class="container container-form" *ngIf="usersReady === true">
  <form [formGroup]="issueForm">
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Name:</label>
      <div class="col-sm-9">
        <input class="form-control" formControlName="name">
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Type:</label>
      <div class="col-sm-9">
        <select class="form-control" formControlName="type">
          <option value="TASK">Task</option>
          <option value="STORY">Story</option>
          <option value="BUG">Bug</option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Reviewed By:</label>
      <div class="col-sm-9">
        <select class="form-control" formControlName="reviewedBy">
          <option value="No one selected">No one selected</option>
          <option *ngFor="let user of users" value="{{user.username}}">
            {{user.username}}
          </option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Assigned To:</label>
      <div class="col-sm-9">
        <select class="form-control" formControlName="assignedTo">
          <option value="No one selected">No one selected</option>
          <option *ngFor="let user of users" value="{{user.username}}">
            {{user.username}}
          </option>
        </select>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Description:</label>
      <div class="col-sm-9">
        <textarea maxlength="1000" rows="10" class="form-control" formControlName="description">
        </textarea>
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Due Date:</label>
      <div class="col-sm-4">
        <input type="date" formControlName="dueDate">
      </div>
      <div>
        <input type="checkbox" formControlName="dueDateSelected" #dueDateSelected
               (change)="changeDueDateInputEnabled(dueDateSelected.checked)">
      </div>
    </div>
    <div>
      <button class="btn btn-dark" (click)="onSubmit()">Submit Issue</button>
      <button class="btn btn-danger" (click)="discard()">Discard Issue</button>
    </div>
  </form>
</div>
