// prowork-react/src/componenets/RegisterComponent.js
import React from 'react';
import { Link } from 'react-router-dom';
import { HeaderComponent } from './HeaderComponent';
import { register } from '../services/access.service';

class RegisterComponent extends React.Component {

    constructor(props) {
        super(props);
        this.state = {
            username: '',
            password: '',
            confirmPassword: '',
            email: ''
        };
    }

    componentDidMount() {
        document.body.classList = ['gold-background-color'];
    }

    componentWillUnmount() {
        document.body.classList = [];
    }

    handleChange = (event) => {
        let key = event.target.id;
        let value = event.target.value;
        this.setState({
            [key]: value
        });
    }

    onSubmit = (event) => {
        event.preventDefault();
        let { username, password, confirmPassword, email } = this.state;
        console.log(this.state);
        if (password === confirmPassword) {
            register(username, password, email)
                .then((response) => {
                    this.props.history.push('/login');
                })
                .catch((error) => {

                })
        } else {
            // TODO Implement not matching passwords 
        }
    }

    render() {
        return (
            <div>
                <HeaderComponent />
                <div className="row justify-content-center">
                    <div className="col-sm-6">
                        <div>Create your account</div>
                        <form>
                            <div className="form-group">
                                <input id="username" className="form-control" required={true} placeholder="Username" onChange={this.handleChange} />
                            </div>
                            <div className="form-group">
                                <input type="password" id="password" className="form-control" required placeholder="Password" onChange={this.handleChange} />
                            </div>
                            <div className="form-group">
                                <input type="password" id="confirmPassword" className="form-control" required placeholder="Confirm Password" onChange={this.handleChange} />
                            </div>
                            <div className="form-group">
                                <input id="email" className="form-control" required placeholder="Email" onChange={this.handleChange} />
                            </div>
                            <div className="row justify-content-center">
                                <button className="btn mr-3 btn-primary" onClick={this.onSubmit}>Register</button>
                                <Link className="btn ml-3 btn-primary" to='/login'>Go Back</Link>
                            </div>
                            {/* <div className="login-message error-msg">Passwords don't match</div> */}
                        </form>
                    </div>
                </div>
            </div>
        )
    }
}

export default RegisterComponent;

// prowork-app/src/app/register/register.component.ts
import {Component, OnDestroy, OnInit, Renderer2} from '@angular/core';
import {AbstractControl, FormBuilder, FormGroup, Validators} from "@angular/forms";
import {User} from "../model/user";
import {Router} from "@angular/router";
import {AccessService} from "../access.service";

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit, OnDestroy {

  registerForm: FormGroup;
  matchingPasswordsError = false;
  errorMessage: string;
  errorDisplay = false;

  constructor(private fb: FormBuilder, private accessService: AccessService,
              private router: Router, private renderer: Renderer2) {
    this.renderer.addClass(document.body, 'body-color');
    if (localStorage.getItem('Bearer') !== null) {
      this.router.navigateByUrl('/home');
    }
  }

  ngOnDestroy(): void {
    this.renderer.removeClass(document.body, 'body-color');
  }

  ngOnInit() {
    this.registerForm = this.fb.group({
      username: ['', [Validators.required, Validators.minLength(5), Validators.maxLength(20)]],
      password: ['', [Validators.required, Validators.minLength(5), Validators.maxLength(25)]],
      confirmPassword: ['', [Validators.required]],
      email: ['', [Validators.required, Validators.email]]
    }, {validator: this.matchingPasswordsValidator});
  }

  onSubmit() {
    const formValue = this.registerForm.value;
    const formData = new FormData();
    formData.set('username', formValue.username);
    formData.set('password', formValue.password);
    formData.set('email', formValue.email);
    this.accessService.register(formData)
      .subscribe(
        (user: User) => {
          console.log(user);
          this.router.navigateByUrl('/login');
        },
        (error: any) => {
          this.errorMessage = error.error.message;
          this.errorDisplay = true;
        }
      );
  }

  goBack() {
    this.router.navigateByUrl('/login');
  }

  matchingPasswordsValidator(control: AbstractControl) {
    if (control.get('password').value !== control.get('confirmPassword').value) {
      return {invalid: true};
    }
  }

}

<app-header></app-header>
<div class="container container-form">
  <div class="login-message">Create your account</div>
  <form [formGroup]="registerForm">
    <div class="form-group row">
      <!--<label class="col-sm-2 col-form-label" for="inputUsername">Username:</label>-->
      <div class="col-sm-12">
        <input id="inputUsername" class="form-control" formControlName="username" placeholder="Username">
      </div>
    </div>
    <div class="form-group row">
      <!--<label class="col-sm-2 col-form-label" for="inputPassword">Password:</label>-->
      <div class="col-sm-12">
        <input type="password" id="inputPassword" class="form-control" formControlName="password"
               placeholder="Password">
      </div>
    </div>
    <div class="form-group row">
      <!--<label class="col-sm-2 col-form-label" for="inputPassword">Password:</label>-->
      <div class="col-sm-12">
        <input type="password" id="inputConfirmPassword" class="form-control" formControlName="confirmPassword"
               placeholder="Confirm Password">
      </div>
    </div>
    <div class="form-group row">
      <!--<label class="col-sm-2 col-form-label" for="inputEmail">Email:</label>-->
      <div class="col-sm-12">
        <input id="inputEmail" class="form-control" formControlName="email" placeholder="Email">
      </div>
    </div>
    <div class="flex-center">
      <button class="btn btn-primary" [disabled]="!registerForm.valid" (click)="onSubmit()">Register</button>
      <button class="btn btn-primary" (click)="goBack()">Go Back</button>
    </div>
    <div *ngIf="!registerForm.get('confirmPassword').untouched && matchingPasswordsError && !errorDisplay"
         class="login-message error-msg">
      Passwords don't match
    </div>
    <div *ngIf="errorDisplay" class="login-message error-msg">
      {{errorMessage}}
    </div>
  </form>
</div>
